### ISSUE TITLE
Add support for elements with OR value fields

### ISSUE THREAD

**Issue by kjmahalingam** [standardhealth/vscode-language-cimpl#15]
If an element's `Value` is `x or y` then the extension cannot handle this case.

**Comment by rutemartins** [comment]
@kjmahalingam I think this might be more than just OR. The extension can't find the definition for `Media`, `Device`, or `Specimen`, but it does find the definition for `FindingResult`, `ExceptionValue`, `DeltaFlag`, `ReferenceRange`, to name a few.

**Comment by kjmahalingam** [comment]
Thanks for bringing that up, @rutemartins. I'll make that something to investigate.
