### ISSUE TITLE
Add `fix` keyword to syntax highlighting

### ISSUE THREAD

**Issue by notpace** [standardhealth/vscode-language-cimpl#4]
`fix related.type to #has-member`

Currently, the`#has-member` code is properly highlighted, but `fix` is not.  It should have similar coloring to other map keywords like `maps to`

**Comment by okeefm** [comment]
Fixed (ha) in https://marketplace.visualstudio.com/items?itemName=okeefm.vscode-language-cimpl v0.2.0
