### ISSUE TITLE
Exclude keywords from syntax highlighting if they are part of a URL

### ISSUE THREAD

**Issue by notpace** [standardhealth/vscode-language-cimpl#5]
![syntax highlighting weirdness](https://user-images.githubusercontent.com/1328955/41165268-2f46659c-6b0b-11e8-9a23-06d970ab9856.png)

The screenshot above shows two words (`units` and `time`) that are part of a URL and should not be highlighted as if they were keywords.

**Comment by okeefm** [comment]
Fixed in https://marketplace.visualstudio.com/items?itemName=okeefm.vscode-language-cimpl v0.2.0
