### ISSUE TITLE
Inconsistent Grammar Highlighting

### ISSUE THREAD

**Issue by notpace** [standardhealth/vscode-language-cimpl#6]
Of the three allowable Grammar declarations (`DataElement`, `ValueSet`, and `Map`), only `Map` is highlighted.  Either all three should be highlighted or none of them should be.  I would lean toward all of them, since the Grammar declarations are limited to that list.

**Comment by okeefm** [comment]
Fixed in https://marketplace.visualstudio.com/items?itemName=okeefm.vscode-language-cimpl v0.2.0
